version: "3"
services:
  api:
    image: 'my-devices'
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - data:/app/data
    env_file:
      - ./.env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

volumes:
  data: